=== ORCOS/ORCOS/tools/SCL/dist/scl2deps.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

    <xs:element name="Dependencies">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="Skeleton" maxOccurs="unbounded" minOccurs="0"/>
                <xs:element ref="Defines" maxOccurs="unbounded" minOccurs="0"/>
                </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:element name="Skeleton">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="Name" type="xs:string" maxOccurs="1"  minOccurs="1" />
                <xs:element ref="Superclasses" maxOccurs="1" minOccurs="1" />
                <xs:element ref="Member" maxOccurs="unbounded" minOccurs="0" />
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:element name="Member">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="Name" type="xs:string" maxOccurs="1"  minOccurs="1" />
                <xs:element ref="Classes" maxOccurs="1" minOccurs="0" />
            </xs:sequence>
        </xs:complexType>
    </xs:element>


  <xs:element name="Class">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="Property" maxOccurs="unbounded"  minOccurs="0" />
      </xs:sequence>
      <xs:attribute name="Name" type="xs:string" use="required"/>
      <xs:attribute name="Requires" type="xs:string" use="optional"/>
    </xs:complexType>
  </xs:element>

  <xs:element name="Property">
    <xs:complexType>
       <xs:attribute name="Name" type="xs:string" use="required"/>
       <xs:attribute name="Type" type="xs:string" use="required"/>
       <xs:attribute name="Optional" type="xs:boolean" use="optional"/>
       <xs:attribute name="Description" type="xs:string" use="optional"/>
    </xs:complexType>
  </xs:element>

  <xs:element name="PropertyValue">
    <xs:complexType>
      <xs:attribute name="Name" type="xs:string" use="required"/>
      <xs:attribute name="Value" type="xs:string" use="required"/>
    </xs:complexType>
  </xs:element>


  <xs:element name="Defaults">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="PropertyValue" maxOccurs="unbounded"  minOccurs="0" />
      </xs:sequence>
      <xs:attribute name="Class" type="xs:string"/>
    </xs:complexType>
  </xs:element>

  <xs:element name="MemberRef">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="Defaults" maxOccurs="unbounded"  minOccurs="0" />
      </xs:sequence>
      <xs:attribute name="Name" type="xs:string" use="required"/>
      <xs:attribute name="optional" type="xs:boolean"/>
    </xs:complexType>
  </xs:element>

  <xs:element name="Superclass">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="MemberRef" maxOccurs="unbounded"  minOccurs="0" />
      </xs:sequence>
      <xs:attribute name="Name" type="xs:string" use="required"/>
      <xs:attribute name="Provides" type="xs:string" use="optional"/>
    </xs:complexType>
  </xs:element>


    <xs:element name="Classes">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="Class" maxOccurs="unbounded" minOccurs="1"  />
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:element name="Superclasses">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="Superclass" maxOccurs="unbounded" minOccurs="1" />
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:element name="Defines">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="Define" maxOccurs="unbounded" minOccurs="0" />
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:element name="Define">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="Name" type="xs:string" maxOccurs="1"  minOccurs="1" />
                <xs:element name="Description" type="xs:string" maxOccurs="1" minOccurs="1" />
            </xs:sequence>
        </xs:complexType>
    </xs:element>

</xs:schema>

=== ORCOS/ORCOS/tools/SCL/TestData/scl2deps.xml
<?xml version="1.0" encoding="UTF-8"?>
<Dependencies xmlns:xs="http://www.w3.org/2001/XMLSchema-instance" xs:schemaLocation="http://orcos.cs.uni-paderborn.de/SCL http://orcos.cs.uni-paderborn.de/SCL/scl2deps.xsd">
  	
  	<Skeleton>
  		<Name>ResourceMutex</Name>
	    
  	 	<Member>
	      <Name>Scheduler</Name>
	      <Classes>
	       	<Class>scheduler/RoundRobinThreadScheduler</Class>
	      </Classes>
	     </Member>	
  	</Skeleton>
  	
  		<Skeleton>
  		<Name>SimpleMutex</Name>
  	 	<Member>
	      <Name>Scheduler</Name>
	      <Classes>
	       	<Class>scheduler/RoundRobinThreadScheduler</Class>
	      </Classes>
	     </Member>	
  	</Skeleton>
  	
  	
  	<Skeleton>
		<Name>Semaphore</Name>
		<Member>
			<Name>Scheduler</Name>
			<Classes>
				<Class>scheduler/RoundRobinThreadScheduler</Class>
			</Classes>
		</Member>
	</Skeleton>

	<Skeleton>
		<Name>Thread</Name>
		<Superclasses>
			<Superclass>process/Thread</Superclass>
			<Superclass>process/PriorityThread</Superclass>
		</Superclasses>
	</Skeleton>


	<Skeleton>
		<Name>TheTimer</Name>
		<Superclasses>
			<Superclass>arch/PPC40x/PPC405ProgrammableIntervalTimer</Superclass>
		</Superclasses>
	</Skeleton>


	<Skeleton>
		<Name>MemoryManager</Name>
		<Superclasses>
			<Superclass>mem/LinearMemManager</Superclass>
		</Superclasses>
		<Member>
			<Name>Seg</Name>
			<Classes>
				<Class>mem/MemResource</Class>
			</Classes>
		</Member>
		<Member>
			<Name>HatLayer</Name>
			<Classes>
				<Class>mem/HatLayer</Class>
			</Classes>
		</Member>
	</Skeleton>


	<Skeleton>
		<Name>Board</Name>
		<Superclasses>
			<Superclass>hal/Board</Superclass>
		</Superclasses>
		<Member>
			<Name>Processor</Name>
			<Classes>
				<Class>arch/PPC40x/PPC405FXProcessor</Class>
			</Classes>
		</Member>
		<Member>
			<Name>Watchdog</Name>
			<Classes>
				<Class>arch/PPC40x/PPC405Watchdog</Class>
			</Classes>
		</Member>
		<Member>
			<Name>UART</Name>
			<Classes>
				<Class>arch/PPC40x/Virtex2/OPB_UART_Lite</Class>
			</Classes>
		</Member>
		<Member>
			<Name>LED</Name>
			<Classes>
				<Class>arch/PPC40x/Virtex2/LED</Class>
			</Classes>
		</Member>
		<Member>
			<Name>InterruptHandler</Name>
			<Classes>
				<Class>arch/PPC40x/PPC405InterruptHandler</Class>
			</Classes>
		</Member>
	</Skeleton>

	<Skeleton>
		<Name>Kernel</Name>
		<Superclasses>
			<Superclass>kernel/Kernel</Superclass>
		</Superclasses>
		<Member>
			<Name>Board</Name>
			<Classes>
				<Class>arch/PPC40x/Virtex2/Virtex2Board</Class>
			</Classes>
		</Member>
		<Member>
			<Name>Logger</Name>
			<Classes>
				<Class>debug/Logger</Class>
			</Classes>
		</Member>
	</Skeleton>	
 </Dependencies>
