=== ORCOS/ORCOS/tools/SCL/dist/scl2.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
	
	<xs:element name="Configuration">
		<xs:complexType>
			<xs:sequence>
			<!-- The correct order of Task/Skeleton/Define have to be strictly kept in the xml file! -->
				<xs:element ref="Options" maxOccurs="unbounded" minOccurs="0"/> 
				<xs:element ref="Tasks" maxOccurs="1" minOccurs="0"/> 
				<xs:element ref="SCL" maxOccurs="1" minOccurs="0"/>
				
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	
	
	<xs:element name="Options">
		<xs:complexType>
	    	<xs:sequence>		
	    	<xs:element ref="Logging" maxOccurs="1" minOccurs="0" />
	    	</xs:sequence>
	    </xs:complexType>
	</xs:element>
	
	<xs:element name="Tasks">
		<xs:complexType>
	    	<xs:sequence>		
	    	<xs:element ref="Task" maxOccurs="unbounded" minOccurs="0" />
	    	</xs:sequence>
	    </xs:complexType>
	</xs:element>
	
	<xs:element name="SCL">
		<xs:complexType>
	    	<xs:sequence>		
	    		<xs:element ref="Skeleton" maxOccurs="unbounded" minOccurs="0"/>
				<xs:element ref="Define" maxOccurs="unbounded" minOccurs="0"/>
	    	</xs:sequence>
	    </xs:complexType>
	</xs:element>
	
	
	<xs:element name="Logging">
		<xs:complexType>
	    	<xs:sequence>		
	    		<xs:element ref="Log" maxOccurs="unbounded" minOccurs="0"/>
	    	</xs:sequence>
	    </xs:complexType>
	</xs:element>
	
	<xs:element name="Log">
		<xs:complexType>
	    	<xs:attribute name="Prefix" type="xs:string"/>
	    	<xs:attribute name="Level" type="LogLevel"/>
	    </xs:complexType>
	</xs:element>
	
	<xs:element name="RealTimeOptions">
		<xs:complexType>
			<xs:sequence>		
		    	<xs:element name="Period" type="xs:string" maxOccurs="1" minOccurs="1"/>
		    	<xs:element name="Deadline" type="xs:string" maxOccurs="1" minOccurs="1"/>
		    	<xs:element name="ExecutionTime" type="xs:string" maxOccurs="1" minOccurs="1"/>
	    	</xs:sequence>
	    </xs:complexType>
	</xs:element>
	
	<xs:element name="PriorityOptions">
		<xs:complexType>
			<xs:sequence>		
		       	<xs:element name="InitialPriority" type="xs:string" maxOccurs="1" minOccurs="1" />
	    		<xs:element name="Phase" type="xs:string" maxOccurs="1" minOccurs="1" />
	    		<xs:element ref="RealTimeOptions" maxOccurs="1" minOccurs="0"/>
	    	</xs:sequence>
	    </xs:complexType>
	</xs:element>
	
	
	<xs:simpleType name="LogLevel">
	 	<xs:restriction base="xs:string">
	   		<xs:enumeration value="FATAL"/>
	   		<xs:enumeration value="ERROR"/>
	   		<xs:enumeration value="WARN"/>
	   		<xs:enumeration value="INFO"/>
	   		<xs:enumeration value="DEBUG"/>
	   		<xs:enumeration value="TRACE"/>
	    </xs:restriction>
	</xs:simpleType>

	<xs:element name="Task">
		<xs:complexType>
	    	<xs:sequence>		
	    		<xs:element name="Start" type="xs:string" maxOccurs="1"	minOccurs="1" />
	    		<xs:element name="Size" type="xs:string" maxOccurs="1"	minOccurs="1" />
	    		<xs:element name="HeapAlign" type="xs:string" maxOccurs="1"	minOccurs="0" />
	    		<xs:element name="Path" type="xs:string" maxOccurs="1"	minOccurs="1" />
	    		<xs:element name="Arguments" type="xs:string" maxOccurs="1"   minOccurs="0" />	    		
				<xs:element ref="PriorityOptions" maxOccurs="1" minOccurs="0"/>	
				<xs:element name="Vma" type="xs:string" maxOccurs="1" minOccurs="0" />
	    	</xs:sequence>
	    </xs:complexType>
	</xs:element>
	
	 <xs:element name="Define">
		<xs:complexType>
	    	<xs:sequence>
	    		<xs:element name="Name" type="xs:string" maxOccurs="1"	minOccurs="1" />
	    		<xs:element name="Value" type="xs:string" maxOccurs="1" minOccurs="1" />
	    	</xs:sequence>
	    </xs:complexType>
	</xs:element>
	
	<xs:element name="Skeleton">
		<xs:complexType>
	    	<xs:sequence>		
	    		<xs:element name="Name" type="xs:string" maxOccurs="1"	minOccurs="1" />
	    		<xs:element name="Superclass" type="xs:string" maxOccurs="1" minOccurs="0" />
	    		<xs:element ref="Member" maxOccurs="unbounded" minOccurs="0" />
	    	</xs:sequence>
	    </xs:complexType>
	</xs:element>
  
  <xs:element name="PropertyValue">
    <xs:complexType>
      <xs:attribute name="Name" type="xs:string" use="required"/>
      <xs:attribute name="Value" type="xs:string" use="required"/>
	  <xs:attribute name="Type" type="xs:string" use="required"/>
    </xs:complexType>
  </xs:element>
  
	<xs:element name="Member">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="PropertyValue" maxOccurs="unbounded" minOccurs="0"/>
			</xs:sequence>
      <xs:attribute name="Name" type="xs:string" use="required"/>
      <xs:attribute name="Class" type="xs:string" use="optional"/>
      <xs:attribute name="None" type="xs:boolean" use="required"/>
      <xs:attribute name="UserSpace" type="xs:boolean" use="optional"/>
      <xs:attribute name="PhyLoadAddress" type="xs:string" use="optional"/>
		</xs:complexType>
	</xs:element>
	
	

	

</xs:schema>

=== ORCOS/ORCOS/tools/SCL/TestData/SCLConfig.xml
<?xml version="1.0" encoding="UTF-8"?>
<Configuration xmlns:xs="http://www.w3.org/2001/XMLSchema-instance"
	xs:schemaLocation="http://orcos.cs.uni-paderborn.de/SCL http://orcos.cs.uni-paderborn.de/SCL/scl2.xsd">

	<Options>
		<Logging>
			<Log Prefix="KERNEL" Level="FATAL"/>
			<Log Prefix="MEM" Level="FATAL"/>
			<Log Prefix="PROCESS" Level="FATAL"/>
			<Log Prefix="SCHEDULER" Level="FATAL"/>
			<Log Prefix="SYNCHRO" Level="FATAL"/>
			<Log Prefix="SYSCALLS" Level="FATAL"/>
			<Log Prefix="DB" Level="FATAL"/>
			<Log Prefix="HAL" Level="FATAL"/>
			<Log Prefix="ARCH" Level="FATAL"/>
			<Log Prefix="FILESYSTEM" Level="FATAL"/>
			<Log Prefix="COMM" Level="FATAL"/>
		</Logging>
	</Options>

<Tasks>
	<Task>
		<Start>0x60000</Start>
		<End>0x6FFFF</End>
		<Heap>0x68000</Heap>
		<Vma>0x50000</Vma>
		<Path>TestData/RTTask1/</Path>
		
		<PriorityOptions>
             <InitialPriority>1234</InitialPriority>
             <Phase>123</Phase>
             <RealTimeOptions>
	            <Period>2</Period>
	            <Deadline>3</Deadline>
	            <ExecutionTime>4</ExecutionTime>
             </RealTimeOptions>
        </PriorityOptions> 
               
               
	</Task>
  	
  	
</Tasks>
	
	<SCL>
		<Skeleton>
			<Name>GenericSuperClassTest</Name>
			<Superclass>dyn/Configurable</Superclass>
			<Template>
				<Parameter>Type1</Parameter>
				<Parameter>Type2</Parameter>
				<Parameter>Type3</Parameter>
			</Template>
		</Skeleton>
		
		<Skeleton>
			<Name>GenericTester</Name>
			<Member>
				<Name>Normal</Name>
				<Class>my/class</Class>
				
			</Member>
			<Member>
				<Name>Generic</Name>
				<Class>my/GenericClass</Class>
				<Template>
					<Parameter>Type1</Parameter>
					<Parameter>Type2</Parameter>
					<Parameter>Type3</Parameter>
				</Template>
			</Member>
		</Skeleton>
		
		
		<Skeleton>
			<Name>ResourceMutex</Name>
			<Member>
				<Name>Scheduler</Name>
				<Class>scheduler/RoundRobinThreadScheduler</Class>
			</Member>
		</Skeleton>
	
	
		<Skeleton>
			<Name>SimpleMutex</Name>
			<Member>
				<Name>Scheduler</Name>
				<Class>scheduler/RoundRobinThreadScheduler</Class>
			</Member>
		</Skeleton>
	
		<Skeleton>
			<Name>Semaphore</Name>
			<Member>
				<Name>Scheduler</Name>
				<Class>scheduler/RoundRobinThreadScheduler</Class>
			</Member>
		</Skeleton>
	
		<Skeleton>
			<Name>Thread</Name>
			<Superclass>process/Thread</Superclass>
		</Skeleton>
	
	
		<Skeleton>
			<Name>TheTimer</Name>
			<Superclass>arch/PPC40x/PPC405ProgrammableIntervalTimer</Superclass>
		</Skeleton>
	
		<Skeleton>
			<Name>TheClock</Name>
			<Superclass>arch/PPC40x/PPC405Clock</Superclass>
		</Skeleton>
	
		<Skeleton>
			<Name>MemoryManager</Name>
			<Superclass>mem/LinearMemManager</Superclass>
			<Member>
				<Name>Seg</Name>
				<Class>mem/MemResource</Class>
			</Member>
			<Member>
				<Name>HatLayer</Name>
				<Class>mem/HatLayer</Class>
				<None>true</None>
			</Member>
		</Skeleton>
	
	
		<Skeleton>
			<Name>Board</Name>
			<Superclass>hal/Board</Superclass>
			<Member>
				<Name>Processor</Name>
				<Class>arch/PPC40x/PPC405FXProcessor</Class>
			</Member>
			<Member>
				<Name>Watchdog</Name>
				<Class>arch/PPC40x/PPC405Watchdog</Class>
				<Constructor>&amp;watchdog</Constructor>
			</Member>
			<Member>
				<Name>UART</Name>
				<Class>arch/PPC40x/Virtex2/OPB_UART_Lite</Class>
				<Constructor>"serial0",OPB_UART_LITE_BASE</Constructor>
			</Member>
			<Member>
				<Name>LED</Name>
				<Class>arch/PPC40x/Virtex2/LED</Class>
				<Constructor>"led0"</Constructor>
			</Member>
			<Member>
				<Name>InterruptHandler</Name>
				<Class>arch/PPC40x/PPC405InterruptHandler</Class>
			</Member>
		</Skeleton>
	
	
		<Skeleton>
			<Name>Kernel</Name>
			<Superclass>kernel/Kernel</Superclass>
			<Member>
				<Name>Board</Name>
				<Class>arch/PPC40x/Virtex2/Virtex2Board</Class>
			</Member>
			<Member>
				<Name>Logger</Name>
				<Class>debug/Logger</Class>
			</Member>
			<Member>
				<Name>Clock</Name>
				<Class>arch/PPC40x/PPC405Clock</Class>
				<Constructor>"clock"</Constructor>
			</Member>
		</Skeleton>
	
	
		<!--  DEFINES -->
		<Define>
			<Name>OPB_UART_LITE_BASE</Name>
			<Value>0x80000800</Value>
		</Define>
	
		<Define>
			<Name>ENABLE_NESTED_INTERRUPTS</Name>
			<Value>1</Value>
		</Define>
	
	
		<Define>
			<Name>ENABLE_SLEEP_SYSCALL</Name>
			<Value>0</Value>
		</Define>
	
		<!-- ADDRESS PROTOCOLS -->
		<Define>
			<Name>NUM_ADDRESS_PROTOCOLS</Name>
			<Value>1</Value>
		</Define>
	
		<Define>
			<Name>USE_SIMPLE_ADDRESS_PROTOCOL</Name>
			<Value>1</Value>
		</Define>
	
		<!-- TRANSPORT PROTOCOLS -->
		<Define>
			<Name>NUM_TRANSPORT_PROTOCOLS</Name>
			<Value>1</Value>
		</Define>
	
		<Define>
			<Name>USE_SIMPLE_TRANSPORT_PROTOCOL</Name>
			<Value>1</Value>
		</Define>
		
		<!-- Address Resolution Protocol -->
		<Define>
			<Name>USE_ARP</Name>
			<Value>1</Value>
		</Define>
	
		<!-- PROCFS -->
		<Define>
			<Name>HAS_PROCFS_ENABLED</Name>
			<Value>1</Value>
		</Define>
	
</SCL>
</Configuration>

=== ORCOS/ORCOS/configurations/RAPTOR/prototype_01/SCLConfig.xml
<?xml version="1.0" encoding="UTF-8"?>
<Configuration xmlns:xs="http://www.w3.org/2001/XMLSchema-instance" xs:schemaLocation="http://orcos.cs.uni-paderborn.de/SCL http://orcos.cs.uni-paderborn.de/SCL/scl2.xsd">
  <Options>
    <Logging>
      <Log Prefix="KERNEL" Level="INFO" />
      <Log Prefix="MEM" Level="WARN" />
      <Log Prefix="PROCESS" Level="WARN" />
      <Log Prefix="SCHEDULER" Level="WARN" />
      <Log Prefix="SYNCHRO" Level="WARN" />
      <Log Prefix="SYSCALLS" Level="WARN" />
      <Log Prefix="DB" Level="WARN" />
      <Log Prefix="HAL" Level="WARN" />
      <Log Prefix="ARCH" Level="INFO" />
      <Log Prefix="FILESYSTEM" Level="WARN" />
      <Log Prefix="COMM" Level="WARN" />
    </Logging>
  </Options>
  <!-- ************************************
    					Tasks
         ************************************ -->
  <Tasks>
    <Task>
      <Start>0x81100000</Start>
      <End>0x8117FFFF</End>
      <Heap>0x81177000</Heap>
      <Path>./tasks/telnet_server/</Path>
      <PriorityOptions>
        <InitialPriority>0</InitialPriority>
        <Phase>0</Phase>
        <RealTimeOptions>
          <Period>500000</Period>
          <Deadline>500000</Deadline>
          <ExecutionTime>0</ExecutionTime>
        </RealTimeOptions>
      </PriorityOptions>
      <Vma>0x100000</Vma>
    </Task>
  </Tasks>
  <SCL>
    <!-- ************************************
    			Skeleton Board
         ************************************ -->
    <Skeleton>
      <Name>Board</Name>
      <Superclass>arch/PPC40x/RAPTOR/RaptorBoard</Superclass>
      <Member Name="HatLayer" Class="arch/PPC40x/PPC405HatLayer" None="false" UserSpace="false" PhyLoadAddress="0x0" />
      <Member Name="Clock" Class="arch/PPC40x/PPC405Clock" None="false" UserSpace="false" PhyLoadAddress="0x0" />
      <Member Name="Processor" Class="arch/PPC40x/PPC405FXProcessor" None="false" UserSpace="false" PhyLoadAddress="0x0" />
      <Member Name="UART2" Class="arch/none/DummyCharDriver" None="true" UserSpace="false" PhyLoadAddress="0x0" />
      <Member Name="InterruptHandler" Class="arch/PPC40x/PPC405InterruptHandler" None="false" UserSpace="false" PhyLoadAddress="0x0" />
      <Member Name="InterruptController" Class="arch/PPC40x/RAPTOR/OPB_Interrupt_Controller" None="false" UserSpace="false" PhyLoadAddress="0x0" />
      <Member Name="ETH" Class="arch/PPC40x/RAPTOR/PLB_EMAC0" None="false" UserSpace="false" PhyLoadAddress="0x0">
        <PropertyValue Name="Address" Value="0x90000000" Type="unsigned int" />
        <PropertyValue Name="Length" Value="4096" Type="unsigned int" />
        <PropertyValue Name="Name" Value="eth0" Type="char*" />
      </Member>
      <Member Name="UART" Class="arch/PPC40x/RAPTOR/OPB_UART_Lite" None="false" UserSpace="false" PhyLoadAddress="0x0">
        <PropertyValue Name="Address" Value="0x90210000" Type="unsigned int" />
        <PropertyValue Name="Length" Value="16" Type="unsigned int" />
        <PropertyValue Name="Name" Value="serial0" Type="char*" />
      </Member>
      <Member Name="LED" Class="arch/PPC40x/RAPTOR/LED" None="false" UserSpace="false" PhyLoadAddress="0x0">
        <PropertyValue Name="Address" Value="0x90220000" Type="unsigned int" />
        <PropertyValue Name="Length" Value="16" Type="unsigned int" />
        <PropertyValue Name="Name" Value="led0" Type="char*" />
      </Member>
      <Member Name="Timer" Class="arch/PPC40x/PPC405ProgrammableIntervalTimer" None="false" UserSpace="false" PhyLoadAddress="0x0" />
    </Skeleton>
    <!-- ************************************
    			Skeleton Kernel
         ************************************ -->
    <Skeleton>
      <Name>Kernel</Name>
      <Superclass>kernel/Kernel</Superclass>
      <Member Name="MigrationManager" Class="migration/MigrationManager" None="true" UserSpace="false" PhyLoadAddress="0x0" />
      <Member Name="ServiceDiscovery" Class="comm/servicediscovery/SNServiceDiscovery" None="true" UserSpace="false" PhyLoadAddress="0x0" />
      <Member Name="MemoryManager" Class="mem/SequentialFitMemManager" None="false" UserSpace="false" PhyLoadAddress="0x0">
        <PropertyValue Name="LastFit" Value="0" Type="unsigned int" />
      </Member>
      <Member Name="Thread" Class="process/RealTimeThread" None="false" UserSpace="false" PhyLoadAddress="0x0" />
      <Member Name="Dispatcher" Class="scheduler/SingleCPUDispatcher" None="false" UserSpace="false" PhyLoadAddress="0x0" />
      <Member Name="Scheduler" Class="scheduler/EarliestDeadlineFirstThreadScheduler" None="false" UserSpace="false" PhyLoadAddress="0x0" />
      <Member Name="Logger" Class="debug/Logger" None="false" UserSpace="false" PhyLoadAddress="0x0" />
      <Member Name="PowerManager" Class="hal/PowerManager" None="false" UserSpace="false" PhyLoadAddress="0x0" />
      <Member Name="TaskManager" Class="process/TaskManager" None="false" UserSpace="false" PhyLoadAddress="0x0" />
    </Skeleton>
    <!-- ************************************
    			Skeleton SyscallManager
         ************************************ -->
    <Skeleton>
      <Name>SyscallManager</Name>
      <Superclass>syscalls/SyscallManager</Superclass>
      <Member Name="sleep" None="false" />
      <Member Name="thread_create" None="false" />
      <Member Name="thread_run" None="false" />
      <Member Name="thread_self" None="false" />
      <Member Name="thread_yield" None="false" />
      <Member Name="signal_wait" None="false" />
      <Member Name="signal_signal" None="false" />
      <Member Name="fputc" None="false" />
      <Member Name="fgetc" None="false" />
      <Member Name="fcreate" None="false" />
      <Member Name="fopen" None="false" />
      <Member Name="fclose" None="false" />
      <Member Name="fwrite" None="false" />
      <Member Name="fread" None="false" />
      <Member Name="new" None="false" />
      <Member Name="delete" None="false" />
      <Member Name="socket" None="false" />
      <Member Name="connect" None="false" />
      <Member Name="listen" None="false" />
      <Member Name="bind" None="false" />
      <Member Name="sendto" None="false" />
      <Member Name="recv" None="false" />
      <Member Name="add_devaddr" None="false" />
      <Member Name="task_stop" None="false" />
      <Member Name="task_resume" None="false" />
      <Member Name="ioctl" Class="" None="false" UserSpace="false" PhyLoadAddress="0x0" />
    </Skeleton>
    <!--  DEFINES -->
    <Define>
      <Name>ENABLE_NESTED_INTERRUPTS</Name>
      <Value>0</Value>
    </Define>
    <!-- PROCFS -->
    <Define>
      <Name>HAS_PROCFS_ENABLED</Name>
      <Value>1</Value>
    </Define>
    <!--  Worker Task configuration -->
    <Define>
      <Name>USE_WORKERTASK</Name>
      <Value>1</Value>
    </Define>
    <Define>
      <Name>NUM_WORKERTHREADS</Name>
      <Value>2</Value>
    </Define>
    <!-- logical Memory addresses -->
    <Define>
      <Name>LOG_TASK_SPACE_START</Name>
      <Value>0x100000</Value>
    </Define>
    <Define>
      <Name>NUM_ADDRESS_PROTOCOLS</Name>
      <Value>0</Value>
    </Define>
    <Define>
      <Name>NUM_TRANSPORT_PROTOCOLS</Name>
      <Value>0</Value>
    </Define>
    <Define>
      <Name>USE_SIMPLEADDRESSPROTOCOL</Name>
      <Value>0</Value>
    </Define>
    <Define>
      <Name>USE_ARP</Name>
      <Value>0</Value>
    </Define>
    <Define>
      <Name>USE_SIMPLETRANSPORTPROTOCOL</Name>
      <Value>0</Value>
    </Define>
    <Define>
      <Name>MMIO_START_ADDRESS</Name>
      <Value>0x48000000</Value>
    </Define>
    <Define>
      <Name>MMIO_AREA_LENGTH</Name>
      <Value>0xFFFFFF</Value>
    </Define>
    <Define>
      <Name>ICACHE_ENABLE</Name>
      <Value>1</Value>
    </Define>
    <Define>
      <Name>DCACHE_ENABLE</Name>
      <Value>1</Value>
    </Define>
    <Define>
      <Name>DEFAULT_USER_STACK_SIZE</Name>
      <Value>4096</Value>
    </Define>
    <Define>
      <Name>STACK_GROWS_DOWNWARDS</Name>
      <Value>1</Value>
    </Define>
    <Define>
      <Name>RESERVED_BYTES_FOR_STACKFRAME</Name>
      <Value>12</Value>
    </Define>
    <Define>
      <Name>CLEAR_THREAD_STACKS</Name>
      <Value>1</Value>
    </Define>
    <Define>
      <Name>WORKERTHREAD_STACK_SIZE</Name>
      <Value>4096</Value>
    </Define>
    <Define>
      <Name>WORKERTHREAD_UART_PRIORITY_PARAM</Name>
      <Value>5000</Value>
    </Define>
    <Define>
      <Name>WORKERTHREAD_ETH_PRIORITY_PARAM</Name>
      <Value>2000</Value>
    </Define>
    <Define>
      <Name>USE_SAFE_KERNEL_STACKS</Name>
      <Value>0</Value>
    </Define>
    <Define>
      <Name>KERNEL_STACK_SIZE</Name>
      <Value>4096</Value>
    </Define>
    <Define>
      <Name>ALIGN_VAL</Name>
      <Value>4</Value>
    </Define>
    <Define>
      <Name>__EARLY_SERIAL_SUPPORT__</Name>
      <Value>1</Value>
    </Define>
    <Define>
      <Name>__DEBUG__</Name>
      <Value>0</Value>
    </Define>
    <Define>
      <Name>RAM_SIZE</Name>
      <Value>512 MB</Value>
    </Define>
  </SCL>
</Configuration>

=== ORCOS/ORCOS/configurations/ATMEGA328/MicroFunkBoard/SCLConfig.xml
<?xml version="1.0" encoding="UTF-8"?>
<Configuration xmlns:xs="http://www.w3.org/2001/XMLSchema-instance" xs:schemaLocation="http://orcos.cs.uni-paderborn.de/SCL http://orcos.cs.uni-paderborn.de/SCL/scl2.xsd">
  <Options>
    <Logging>
      <Log Prefix="KERNEL" Level="INFO" />
      <Log Prefix="MEM" Level="WARN" />
      <Log Prefix="PROCESS" Level="WARN" />
      <Log Prefix="SCHEDULER" Level="WARN" />
      <Log Prefix="SYNCHRO" Level="WARN" />
      <Log Prefix="SYSCALLS" Level="WARN" />
      <Log Prefix="DB" Level="WARN" />
      <Log Prefix="HAL" Level="WARN" />
      <Log Prefix="ARCH" Level="INFO" />
      <Log Prefix="FILESYSTEM" Level="WARN" />
      <Log Prefix="COMM" Level="WARN" />
    </Logging>
  </Options>
  <!-- ************************************
    					Tasks
         ************************************ -->
  <Tasks />
  <SCL>
    <!-- ************************************
    			Skeleton Board
         ************************************ -->
    <Skeleton>
      <Name>Board</Name>
      <Superclass>arch/Atmel/ATMEGA328/RN-MicroFunk/MicroFunkBoard</Superclass>
      <Member Name="HatLayer" Class="hal/HatLayer" None="true" UserSpace="false" PhyLoadAddress="0x0" />
      <Member Name="Clock" Class="hal/EmulatedClock" None="false" UserSpace="false" PhyLoadAddress="0x0" />
      <Member Name="Processor" Class="arch/Atmel/ATMEGA328/ATMEGA328Processor" None="false" UserSpace="false" PhyLoadAddress="0x0" />
      <Member Name="Timer" Class="arch/Atmel/ATMEGA328/Timer1" None="false" UserSpace="false" PhyLoadAddress="0x0" />
    </Skeleton>
    <!-- ************************************
    			Skeleton Kernel
         ************************************ -->
    <Skeleton>
      <Name>Kernel</Name>
      <Superclass>kernel/Kernel</Superclass>
      <Member Name="MigrationManager" Class="migration/MigrationManager" None="true" UserSpace="false" PhyLoadAddress="0x0" />
      <Member Name="ServiceDiscovery" Class="comm/servicediscovery/SNServiceDiscovery" None="true" UserSpace="false" PhyLoadAddress="0x0" />
      <Member Name="MemoryManager" Class="mem/LinearMemManager" None="false" UserSpace="false" PhyLoadAddress="0x0">
        <PropertyValue Name="LastFit" Value="0" Type="unsigned int" />
      </Member>
      <Member Name="Thread" Class="process/Thread" None="false" UserSpace="false" PhyLoadAddress="0x0" />
      <Member Name="Dispatcher" Class="scheduler/SingleCPUDispatcher" None="false" UserSpace="false" PhyLoadAddress="0x0" />
      <Member Name="Scheduler" Class="scheduler/SingleThreadScheduler" None="false" UserSpace="false" PhyLoadAddress="0x0" />
      <Member Name="Logger" Class="debug/Logger" None="true" UserSpace="false" PhyLoadAddress="0x0" />
      <Member Name="PowerManager" Class="hal/PowerManager" None="false" UserSpace="false" PhyLoadAddress="0x0" />
      <Member Name="TaskManager" Class="process/TaskManager" None="false" UserSpace="false" PhyLoadAddress="0x0" />
      <Member Name="RamManager" Class="mem/NoRamManager" None="true" UserSpace="false" PhyLoadAddress="0x0" />
    </Skeleton>
    <Skeleton>
      <Name>FileSystems</Name>
      <Superclass>filesystem/SimpleFileManager</Superclass>
      <Member Name="PartitionManager" Class="filesystem/PartitionManager" None="true" UserSpace="false" PhyLoadAddress="0x0" />
      <Member Name="DOSPartition" Class="filesystem/DOSPartition" None="true" UserSpace="false" PhyLoadAddress="0x0" />
      <Member Name="FATFileSystem" Class="filesystem/FATFileSystem" None="true" UserSpace="false" PhyLoadAddress="0x0" />
    </Skeleton>
    <Skeleton>
      <Name>USBDriver</Name>
      <Superclass>usb/USBDeviceDriverLibrary</Superclass>
      <Member Name="Factory" Class="usb/USBDeviceDriverFactory" None="true" UserSpace="false" PhyLoadAddress="0x0" />
      <Member Name="SMSC95xx" Class="usb/SMSC95xxUSBDeviceDriver" None="true" UserSpace="false" PhyLoadAddress="0x0" />
      <Member Name="MassStorage" Class="usb/MassStorageSCSIUSBDeviceDriver" None="true" UserSpace="false" PhyLoadAddress="0x0" />
    </Skeleton>
    <!-- ************************************
    			Skeleton SyscallManager
         ************************************ -->
    <Skeleton>
      <Name>SyscallManager</Name>
      <Superclass>syscalls/SyscallManager</Superclass>
      <Member Name="sleep" None="true" />
      <Member Name="thread_create" None="true" />
      <Member Name="thread_run" None="true" />
      <Member Name="thread_self" None="false" />
      <Member Name="thread_yield" None="false" />
      <Member Name="signal_wait" None="true" />
      <Member Name="signal_signal" None="true" />
      <Member Name="fputc" None="false" />
      <Member Name="fgetc" None="false" />
      <Member Name="fcreate" None="false" />
      <Member Name="fopen" None="false" />
      <Member Name="fclose" None="false" />
      <Member Name="fwrite" None="false" />
      <Member Name="fread" None="false" />
      <Member Name="new" None="false" />
      <Member Name="delete" None="false" />
      <Member Name="socket" None="true" />
      <Member Name="connect" None="true" />
      <Member Name="listen" None="true" />
      <Member Name="bind" None="true" />
      <Member Name="sendto" None="true" />
      <Member Name="recv" None="true" />
      <Member Name="add_devaddr" None="true" />
      <Member Name="task_stop" None="true" />
      <Member Name="task_resume" None="true" />
      <Member Name="ioctl" Class="" None="false" UserSpace="false" PhyLoadAddress="0x0" />
      <Member Name="thread_wait" Class="" None="true" UserSpace="false" PhyLoadAddress="0x0" />
      <Member Name="fstat" Class="" None="true" UserSpace="false" PhyLoadAddress="0x0" />
      <Member Name="task_run" Class="" None="true" UserSpace="false" PhyLoadAddress="0x0" />
      <Member Name="task_kill" Class="" None="true" UserSpace="false" PhyLoadAddress="0x0" />
      <Member Name="mapMemory" Class="" None="true" UserSpace="false" PhyLoadAddress="0x0" />
      <Member Name="shm_map" Class="" None="true" UserSpace="false" PhyLoadAddress="0x0" />
    </Skeleton>
    <!--  DEFINES -->
    <Define>
      <Name>ENABLE_NESTED_INTERRUPTS</Name>
      <Value>0</Value>
    </Define>
    <!-- PROCFS -->
    <Define>
      <Name>HAS_PROCFS_ENABLED</Name>
      <Value>0</Value>
    </Define>
    <!--  Worker Task configuration -->
    <Define>
      <Name>USE_WORKERTASK</Name>
      <Value>0</Value>
    </Define>
    <Define>
      <Name>NUM_WORKERTHREADS</Name>
      <Value>2</Value>
    </Define>
    <!-- logical Memory addresses -->
    <Define>
      <Name>LOG_TASK_SPACE_START</Name>
      <Value>0x100000</Value>
    </Define>
    <Define>
      <Name>NUM_ADDRESS_PROTOCOLS</Name>
      <Value>0</Value>
    </Define>
    <Define>
      <Name>NUM_TRANSPORT_PROTOCOLS</Name>
      <Value>0</Value>
    </Define>
    <Define>
      <Name>USE_SIMPLEADDRESSPROTOCOL</Name>
      <Value>0</Value>
    </Define>
    <Define>
      <Name>USE_ARP</Name>
      <Value>0</Value>
    </Define>
    <Define>
      <Name>USE_SIMPLETRANSPORTPROTOCOL</Name>
      <Value>0</Value>
    </Define>
    <Define>
      <Name>MMIO_START_ADDRESS</Name>
      <Value>0x48000000</Value>
    </Define>
    <Define>
      <Name>MMIO_AREA_LENGTH</Name>
      <Value>0xFFFFFF</Value>
    </Define>
    <Define>
      <Name>ICACHE_ENABLE</Name>
      <Value>1</Value>
    </Define>
    <Define>
      <Name>DCACHE_ENABLE</Name>
      <Value>1</Value>
    </Define>
    <Define>
      <Name>DEFAULT_USER_STACK_SIZE</Name>
      <Value>4096</Value>
    </Define>
    <Define>
      <Name>STACK_GROWS_DOWNWARDS</Name>
      <Value>1</Value>
    </Define>
    <Define>
      <Name>RESERVED_BYTES_FOR_STACKFRAME</Name>
      <Value>12</Value>
    </Define>
    <Define>
      <Name>CLEAR_THREAD_STACKS</Name>
      <Value>1</Value>
    </Define>
    <Define>
      <Name>WORKERTHREAD_STACK_SIZE</Name>
      <Value>4096</Value>
    </Define>
    <Define>
      <Name>WORKERTHREAD_UART_PRIORITY_PARAM</Name>
      <Value>5000</Value>
    </Define>
    <Define>
      <Name>WORKERTHREAD_ETH_PRIORITY_PARAM</Name>
      <Value>2000</Value>
    </Define>
    <Define>
      <Name>USE_SAFE_KERNEL_STACKS</Name>
      <Value>0</Value>
    </Define>
    <Define>
      <Name>KERNEL_STACK_SIZE</Name>
      <Value>256</Value>
    </Define>
    <Define>
      <Name>ALIGN_VAL</Name>
      <Value>1</Value>
    </Define>
    <Define>
      <Name>__EARLY_SERIAL_SUPPORT__</Name>
      <Value>1</Value>
    </Define>
    <Define>
      <Name>__DEBUG__</Name>
      <Value>0</Value>
    </Define>
    <Define>
      <Name>RAM_SIZE</Name>
      <Value>512 MB</Value>
    </Define>
    <Define>
      <Name>MAX_NUM_TASKS</Name>
      <Value>1</Value>
    </Define>
    <Define>
      <Name>PRINT_BOOT_LOGO</Name>
      <Value>0</Value>
    </Define>
  </SCL>
</Configuration>
